config/routes.rb
Rails.application.routes.draw do
  root :to => "flights#index"
  resources :flights
  devise_for :users
  resources :users do 
    resources :bookings
  end
  get 'search', to: "categories#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def genrate_pnr_code
    [*('A'..'Z'),*('0'..'9')].shuffle[0,8].join
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  validates :seat_prn, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord

  #relations
  belongs_to :flight
  has_many :seats , dependent: :destroy

  #validations
  validates :seats_in_row, :numbers_of_rows, presence: true

  #callbacks
  after_create :set_pnr_code

  def set_pnr_code
    self.update(pnr_code: genrate_pnr_code)
  end

end

app/models/flight.rb
class Flight < ApplicationRecord

  #relations
  has_many :categories, dependent: :destroy

  #validations
  validates :aeroplan_type, :origin, :destination, presence: true


  FLIGHT_CATEGORIES = ["First_Class", "Business_Class", "Economy_Class"]
  
  def setup_categories_and_seats(options)
    FLIGHT_CATEGORIES.each do |category| 
      category_seat_in_row = options["seats_in_row_for_#{category.downcase}"]
      category_number_of_rows = options["numbers_of_rows_for_#{category.downcase}"]
      created_category = self.categories.create(name: category, seats_in_row: category_seat_in_row, numbers_of_rows: category_number_of_rows)
      number_of_seats= created_category.seats_in_row * created_category.numbers_of_rows
        (1..number_of_seats).each do |num|
          created_category.seats.create(pnr: genrate_pnr_code, seat_type: 1, price: options["seat_price_for_#{category.downcase}"] )
        end
    end
    

  end
  
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { admin: 0, user: 1 }

  has_one :booking

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index
    @booking = current_user.booking
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    seat = Seat.find_by(pnr: booking_params["seat_prn"])
    category_code = seat.category.pnr_code
    respond_to do |format|
      if @booking.save
        seat.update(booked: true)
        format.html { redirect_to user_bookings_path(@booking), notice: "Booking was successfully created." }
      else
        format.html { redirect_to "/search?pnr=#{category_code}&commit=serach", notice: "the seat is booked" }
      end
    end
  end

  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.permit(:seat_prn, :user_id, :price)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def search
    
    @category = Category.find_by(pnr_code: params["pnr"])
    @seats = @category&.seats
  end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  def index
    @flights = Flight.all
  end

  def show
  end

  def new
    @flight = Flight.new
  end

  def edit
  end

  def create

    @flight = Flight.new(aeroplan_type: flight_params["aeroplan_type"], origin: flight_params["origin"], destination: flight_params["destination"])
    
    respond_to do |format|
      if @flight.save
        seats_configs = flight_params.except("aeroplan_type" ,"origin", "destination")
        @flight.setup_categories_and_seats(seats_configs)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:aeroplan_type, :origin, :destination, :seats_in_row_for_first_class, 
                                    :numbers_of_rows_for_first_class, :seats_in_row_for_business_class, :numbers_of_rows_for_business_class, 
                                    :seats_in_row_for_economy_class, :numbers_of_rows_for_economy_class , 
                                    :seat_price_for_first_class ,:seat_price_for_business_class, :seat_price_for_economy_class)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seat_prn %>
    <%= form.text_field :seat_prn %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Seat prn</th>
      <th>User</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @booking.seat_prn %></td>
        <td><%= @booking.user_id %></td>
        <td><%= @booking.price %></td>
      </tr>
  </tbody>
</table>

<br>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seat prn:</strong>
  <%= @booking.seat_prn %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @booking.price %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/categories/search.html.erb
<h1> Serach Results </h1>

<% if @category %>
  <% seats_in_row = @category.seats_in_row %>
  <% numbers_of_rows = @category.numbers_of_rows %>
  <%(0...seats_in_row).each do |num|%>
    <%(0...numbers_of_rows).each do |num2|%>
       <% @seat = @seats[num+num2] %>
       <%= link_to "seat_num_#{@seat.pnr}", "/users/#{current_user.id}/bookings?seat_prn=#{@seat.pnr}&user_id=#{current_user.id}&price=#{@seat.price}" ,method: "post" %>
    <%end%>
    <br>
  <%end%>
<% else %>
  <%= "invalid pnr code" %>
<% end %>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :aeroplan_type %>
    <%= form.text_field :aeroplan_type %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :seats_in_row_for_first_class %>
    <%= form.text_field :seats_in_row_for_first_class %>
  </div>

  <div class="field">
    <%= form.label :numbers_of_rows_for_first_class %>
    <%= form.text_field :numbers_of_rows_for_first_class %>
  </div>

  <div class="field">
    <%= form.label :seat_price_for_first_class %>
    <%= form.text_field :seat_price_for_first_class %>
  </div>

  <div class="field">
    <%= form.label :seats_in_row_for_Business_class %>
    <%= form.text_field :seats_in_row_for_business_class %>
  </div>

  <div class="field">
    <%= form.label :numbers_of_rows_for_Business_class %>
    <%= form.text_field :numbers_of_rows_for_business_class %>
  </div>

  <div class="field">
    <%= form.label :seat_price_for_business_class %>
    <%= form.text_field :seat_price_for_business_class %>
  </div>

  <div class="field">
    <%= form.label :seats_in_row_for_Economy_class %>
    <%= form.text_field :seats_in_row_for_economy_class %>
  </div>

  <div class="field">
    <%= form.label :numbers_of_rows_for_economy_class %>
    <%= form.text_field :numbers_of_rows_for_economy_class %>
  </div>

  <div class="field">
    <%= form.label :seat_price_for_economy_class %>
    <%= form.text_field :seat_price_for_economy_class %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>
<h4> search by pnr code</h4>
  <%= form_tag(search_path , method: :get) do %>
   <%= text_field_tag(:pnr , params[:pnr]) %>
   <%= submit_tag("serach") %>
  <% end %>

<h4 style="margin:0;display:inline;float:left" > create new flight</h4>
<%=  link_to 'Create Flight', new_flight_path %>
<table>
  <thead>
    <tr>
      <th>Aeroplan type</th>
      <th>Origin</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.aeroplan_type %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= link_to 'Show', flight %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aeroplan type:</strong>
  <%= @flight.aeroplan_type %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>
<% if current_user.admin? %>
  <p>  
  <strong>seats in row in first class:</strong>
  <%= @flight.categories&.first&.seats_in_row %>
  </p>
  
  <p>  
  <strong>number of rows in first class:</strong>
  <%= @flight.categories&.first&.numbers_of_rows %>
  </p>
  
  <p>  
  <strong>seats in row in business class:</strong>
  <%= @flight.categories&.second&.seats_in_row %>
  </p>
  
  <p>  
  <strong>number of rows in business class:</strong>
  <%= @flight.categories&.second&.numbers_of_rows %>
  </p>
  
  <p>
    <strong>seats in row in economy class:</strong>
    <%= @flight.categories&.third&.seats_in_row %>
  </p>
  
  <p>
  <strong>number of rows in economy class:</strong>
  <%= @flight.categories&.third&.numbers_of_rows %>
  </p>
<% end %>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
     <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
     <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
     <% end %>
</p>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>